### ISSUE TITLE
Add a template to encourage useful reports

### ISSUE THREAD

**Issue by miketaylr** [abeyad/user-agent-reduction#1]
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by abeyad** [comment]
Thanks Mike, I created a template here: https://github.com/abeyad/user-agent-reduction/blob/main/.github/ISSUE_TEMPLATE/bug-feedback.md.  I'll close this out but if you have more feedback on changes to it, please don't hesitate to comment or open another bug.

**Comment by miketaylr** [comment]
Looks great, thanks!

<img width="947" alt="Screen Shot 2021-08-19 at 9 21 50 PM" src="https://user-images.githubusercontent.com/67283/130164212-cad63e72-f514-47cc-ad5d-a3c17c952a63.png">
