### ISSUE TITLE
User-Agent Reduction deprecation trial registration help

### ISSUE THREAD

**Issue by kumarrishav** [abeyad/user-agent-reduction#13]
**Describe the issue**
A clear and concise description of what the issue is.

For ex: 

Which account should be used while registering for the User-Agent Reduction deprecation trial?  How does it validate that the user who is doing the registration actually owns the domain or subdomain because it's the server/domain owner that infected the token? 

Use case: 
Let's say I own the domain https://www.foo.com
and I want that all users of https://www.foo.com should give full UA.

Is it the presence of `Origin-Trial: <ORIGIN TRIAL TOKEN>` in the response header that tells the owner of the domain or subdomain is the same person who created the token? 

**Environment:**
 - Chrome Version: [obtained from chrome://version]
 - Sites, if applicable: [e.g. youtube.com]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by miketaylr** [comment]
> Is it the presence of Origin-Trial: <ORIGIN TRIAL TOKEN> in the response header that tells the owner of the domain or subdomain is the same person who created the token?

Yes, precisely - if you are able to add a header to the server, that means you are in theory authorized. It's not possible to opt in another origin into an origin trial. Does that answer your question?

**Comment by miketaylr** [comment]
Going to close due to lack of activity.
