### ISSUE TITLE
When will User-Agent Reduction deprecation trial end? 

### ISSUE THREAD

**Issue by kumarrishav** [abeyad/user-agent-reduction#14]
**Describe the issue**
A clear and concise description of what the issue is.

When will User-Agent Reduction deprecation trial is going to end?

**Environment:**
 - Chrome Version: [obtained from chrome://version]
 - Sites, if applicable: [e.g. youtube.com]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by miketaylr** [comment]
If you look at https://developer.chrome.com/origintrials/#/view_trial/2608710084154359809, it shows the expiration date: May 23, 2023.
