### ISSUE TITLE
User Agent is still not reduced on mobile

### ISSUE THREAD

**Issue by MOZGIII** [abeyad/user-agent-reduction#15]
**Describe the issue**
I was inspecting the User Agent behaviour, and found that on mobile devices the User Agent is still presented as `122.0.<non-zero>.<non-zero>` instead of `122.0.0.0` as expected.

**Environment:**
Metadata from https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome

**To Reproduce**
Use Chrome on Android or iOS.

**Expected behavior**
User Agent is reduced to only major version and the rest is filled with zeroes.

**Screenshots**
-

**Additional context**
This is supposed to be completed, and there is even a blog post that explains it, explicitly the mobile behavior: 
https://developers.google.com/privacy-sandbox/blog/user-agent-reduction-android-model-and-version
It is clearly supposed to work now.

**Comment by miketaylr** [comment]
@MOZGIII can you provide more info on which platform and version you're seeing this on? Screenshots would be useful as well.

Note that this is expected behavior on iOS until it's possible to implement support for UA Client Hints.

**Comment by MOZGIII** [comment]
I only got this:

<img width="741" alt="image" src="https://github.com/miketaylr/user-agent-reduction/assets/265507/3b25692f-2277-4d5c-8a3c-5e905613bd3d">

The data looks accurate though.

If you have a mobile device around you can try visiting https://browserleaks.com/client-hints see for yourself if it works.

**Comment by MOZGIII** [comment]
> Note that this is expected behavior on iOS until it's possible to implement support for UA Client Hints.

What about the Android though?

The iOS I get because the WebKit seems to be used instead of Blink there...

**Comment by miketaylr** [comment]
That would be a bug on Android - but I'm not able to reproduce.

**Comment by MOZGIII** [comment]
Oh, I'll ask someone with a device to confirm.

UPD: it works! Bad data on the website.

**Comment by MOZGIII** [comment]
Ok, this clarifies things for me. The only offender is iOS then.
Should I close this one and open another one?

The iOS inconsistency should probably be clarified in the blog post I mentioned in the issue posting.

**Comment by miketaylr** [comment]
> Should I close this one and open another one?

Not sure an issue here is super productive - since the intent was to capture issues related to the Origin Trial and there's no real bug. We have documented elsewhere that this is Android-only, but if you find the existing docs confusing - feel free to raise feedback against that.

**Comment by MOZGIII** [comment]
Thanks for the quick response!
