### ISSUE TITLE
Critical-CH and Accept-CH during Origin Trial

### ISSUE THREAD

**Issue by bvattikonda** [abeyad/user-agent-reduction#3]
The origin trial documentation refers to: 

-- quote begin
Setting Accept-CH will only cause the reduced User-Agent string to be sent on subsequent requests to the origin; to resend the first navigation request with the reduced User-Agent string, add Critical-CH: Sec-CH-UA-Reduced to your HTTP response header, in addition to the Accept-CH and Origin-Trial headers.
-- quote end

[Source](https://developer.chrome.com/blog/user-agent-reduction-origin-trial/#how-do-i-participate-in-the-user-agent-reduction-origin-trial)

Can this feature be used now before [crbug.com/1188199](https://crbug.com/1188199) is fixed?

**Comment by miketaylr** [comment]
> Can this feature be used now before [crbug.com/1188199](https://crbug.com/1188199) is fixed?

This is the (non-public) launch bug for TLS `ACCEPT_CH`, which is not yet shipped due to stability issues.

`Critical-CH` is in the process of being rolled out to Chrome stable users now, and is safe to use with HTTP `Accept-CH` (though it's currently a subset of the release population).

**Comment by wabi91** [comment]
When a custom value is added to the user agent, can the additional value be still used without deleting the value regardless of `UA reduction`?

```
UA + "Plus and Road"
```

It's a question about whether the custom UA can't be used with that function `UA reduction`.

Ref docs link: https://www.chromium.org/updates/ua-reduction
