### ISSUE TITLE
User-Agent header is not right for 302 direct when chrome devtool is switched to mobile mode.

### ISSUE THREAD

**Issue by INCHMAN1900** [abeyad/user-agent-reduction#4]
**Describe the issue**

When in mobile mode, the devtool will send mobile User-Agent header to the server. If the server responds with a 302 redirect, chrome will follow the request to the Location, but with chrome's original User-Agent.

**Environment:**

 - Chrome Version: 95.0.4638.54 (正式版本) (x86_64)
 - OS: MacOS
 - Sites, if applicable: [This site](https://app.mokahr.com/campus-recruitment/officialqa/43919#/home)

**To Reproduce**

visit [this site](https://app.mokahr.com/campus-recruitment/officialqa/43919#/home) under mobile mode in devtool.

You'll find two 302 request in the network panel. The first is sent with `Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1`. The second is sent with `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36`

**Expected behavior**

Both requests are sent with `Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1`

**Screenshots**

first request:
<img width="967" alt="截屏2021-10-26 下午5 48 20" src="https://user-images.githubusercontent.com/20406631/138854247-e1d43fe1-9dc7-434f-919a-9ffcf93aeaca.png">

second request:
<img width="968" alt="截屏2021-10-26 下午5 48 34" src="https://user-images.githubusercontent.com/20406631/138854286-50e40378-1867-448c-b695-b1605ca42357.png">

**Additional context**

chrome 94 is fine. So I suppose this is a problem in chrome 95

**Comment by abeyad** [comment]
Thanks for the report @INCHMAN1900!  

Did you have the [User-Agent Reduction origin trial ](https://developer.chrome.com/origintrials/#/view_trial/-7123568710593282047) enabled on your site?  I don't see signs of having the UA reduction origin trial enabled in your request headers screen shot, but just wanted to confirm.  This could be a regression in the User-Agent handling irrespective of whether the origin trial is enabled or not.

**Comment by INCHMAN1900** [comment]
> Thanks for the report @INCHMAN1900!
> 
> Did you have the [User-Agent Reduction origin trial ](https://developer.chrome.com/origintrials/#/view_trial/-7123568710593282047) enabled on your site? I don't see signs of having the UA reduction origin trial enabled in your request headers screen shot, but just wanted to confirm. This could be a regression in the User-Agent handling irrespective of whether the origin trial is enabled or not.

I've tried to set `Reduce User-Agent request header` in `chrome://flags` to `true` or `false`, and it doesn't matter.

**Comment by abeyad** [comment]
Note: This was also reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1263639.

**Comment by INCHMAN1900** [comment]
> Note: This was also reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1263639.

Thx.

**Comment by abeyad** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/3251922 is up, which should fix the issue (tested it manually as well)

**Comment by abeyad** [comment]
This was fixed for M97: https://chromium-review.googlesource.com/c/chromium/src/+/3251922
And was back-ported to M96: https://chromium-review.googlesource.com/c/chromium/src/+/3258067
