### ISSUE TITLE
UA reduction not working on Android Webview

### ISSUE THREAD

**Issue by adrigzr** [abeyad/user-agent-reduction#5]
**Describe the issue**
UA reduction not working on Android Webview.

**Environment:**
 - Chrome Version: 97
 - OS: Android 9
 - Sites, if applicable: -

**To Reproduce**

1. Download [Webview Test](https://play.google.com/store/apps/details?id=com.snc.test.webview2&hl=es&gl=US)
2. Open a valid url with trial enrolled inside webview
3. Check chrome://inspect to see evidences

**Expected behavior**
UA should be reduced.

**Screenshots**

Evidences on Webview Test:

![Screenshot 2022-01-07 at 13 18 58](https://user-images.githubusercontent.com/7289287/148543532-5f6d6ac3-1fb4-4498-b5e0-72a00658bad6.png)
![Screenshot 2022-01-07 at 13 19 09](https://user-images.githubusercontent.com/7289287/148543535-1db092ba-b11b-4d63-aa96-c67eb4dad939.png)

Evidences on Chrome:

![Screenshot 2022-01-07 at 13 20 18](https://user-images.githubusercontent.com/7289287/148543585-b7584504-4956-4808-a511-4491357889e6.png)
![Screenshot 2022-01-07 at 13 20 25](https://user-images.githubusercontent.com/7289287/148543584-214e4a70-0f21-466a-98c8-659957fa4c1f.png)

**Additional context**

I prefer to not publish my trial origin, but as seen in evidences it is well configured.

**Comment by abeyad** [comment]
Hi Adrian - thanks for the bug report!  This is actually working as intended.  We are not reducing the UA string on WebView, primarily because client hints are not yet available on WebView.  Here's the tracking bug for client hints on WebView: crbug.com/921655.

Since this is intended behavior, I'll close the bug out, but if you have any further questions, please don't hesitate to ask.

**Comment by abeyad** [comment]
I've also sent a PR to update the blog post to note that the origin trial isn't meant to include WebView and iOS.

**Comment by adrigzr** [comment]
@abeyad, great to know! We were worried about it! Regards.
