### ISSUE TITLE
Custom User-Agent

### ISSUE THREAD

**Issue by wabi91** [abeyad/user-agent-reduction#6]
**Describe the issue**
When a custom value is added to the user agent, can the additional value be still used without deleting the value regardless of `UA reduction`?

It's a question about whether the custom UA can't be used with that function `UA reduction`.

**Environment:**
 - Chrome Version: over 93
 - OS: Android

**Additional context**
```
UA + "Plus and Road"
```

Ref docs link: https://www.chromium.org/updates/ua-reduction

**Comment by abeyad** [comment]
I'm not sure I follow the question, but if you are asking whether a custom UA will get overridden by UA reduction, the answer is no.  The custom UA is preserved and we won't attempt to alter it or "reduce" it in any way.

Does that answer your question?

**Comment by wabi91** [comment]
> The custom UA is preserved and we won't attempt to alter it or "reduce" it in any way.

It does.
Thank you for answering.
