### ISSUE TITLE
Bots related information

### ISSUE THREAD

**Issue by runesam** [abeyad/user-agent-reduction#7]
The UA reduction is aiming to reduce the information available on the UA to be only about the following:

1. The browser's brand (name).
2. The browser’s significant version.
3. A desktop or mobile distinction. E.g having either mobile or desktop keywords in the user agent string.
4. The platform the browser is running on. (By definition A platform consists of an operating system, and the hardware).

Given the following examples of a user agent of a bot coming from Chrome:

```diff
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) Chrome/98.0.4758.102 Mobile Safari/537.36
- AppleWebKit/537.36 (KHTML, like Gecko) 
+ (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```
```diff
Mozilla/5.0 (X11; Linux x86_64) Chrome/56.0.2924.87 Safari/537.36
- AppleWebKit/537.36 (KHTML, like Gecko)
+ Google-PageRenderer Google (+https://developers.google.com/+/web/snippet/)
```

![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) refers to the software or the library that hosts the browser, also a contact/referrer to the developer/author of that software/library.
![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+) refers to the rendering and the layout engine.

as the reduction going to be applied, eventually. I can't rectify whether this information will be available either in the frozen UA string or any of the new UAH.

could someone help clarify this?

**Comment by abeyad** [comment]
Hi Sam - the Googlebot string won't be coming from Chrome, so there's nothing there for us to reduce.  That part of the UA string is constructed by Googlebot and sent in the User-Agent header when crawling the web.

**Comment by runesam** [comment]
Hi @abeyad  thank you for the quick answer.
I didn't know _the Googlebot string won't be coming from Chrome_, so with that being said, the bot related information shall remain available not affected by the proposal reduction.
